# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ef30d76d5b3f86f9fd10b20bd37d2b7b2c1b19bc1d1fcbf667e91b12bda89edbfd951eb93262d840231ddff34e8b9dbf86747cd89640a404960e61fb98dd547

test:
  secret_key_base: 1a4938c43dcd3004ee1a7026764222d5073400317ba5d414084fdbca20cee43513b97a994d6be4a45acca315b653ad5fb698b9e6dc08ae56cf72ca53ced3b0cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
